parameters:
    google_adwordsapi_oauthinfo:
        client_id: "%google_apiclient_clientid%"
        client_secret: "%google_apiclient_clientsecret%"
        
    google_apiclient_scope_userinfo: https://www.googleapis.com/auth/userinfo.email
    google_adwordsapi_scope: https://www.googleapis.com/auth/adwords

    google_apiclient_class: Google_Client
    google_adwordsapi_class: AdWordsUser
    google_utils_class: Mayeco\GoogleBundle\Services\GoogleUtils

services:
    google.apiclient:
        class: %google_apiclient_class%
        calls:
            - [setClientId, ["%google_apiclient_clientid%"]]
            - [setClientSecret, ["%google_apiclient_clientsecret%"]]
            - [setRedirectUri, ["%google_apiclient_redirecturl%"]]
            - [addScope, ["%google_apiclient_scope_userinfo%"]]
            - [addScope, ["%google_adwordsapi_scope%"]]
            - [setAccessType, ["offline"]]

    google.adwordsapi:
        class: %google_adwordsapi_class%
        calls:
            - [SetDeveloperToken, ["%google_adwordsapi_devkey%"]]
            - [SetUserAgent, ["%google_adwordsapi_useragent%"]]
            - [SetClientLibraryUserAgent, ["%google_adwordsapi_clientlib%"]]
            - [SetOAuth2Info, ["%google_adwordsapi_oauthinfo%"]]

    google.utils:
        class: %google_utils_class%
        arguments: ["@google.adwordsapi", "@google.apiclient", "@memcache.default", "%google_adwordsapi_version%"]
