services:
    mayeco_google.apiclient:
        class: Google_Client
        public: false
        calls:
            - [setClientId, ["%mayeco_google.oauthinfo.client_id%"]]
            - [setClientSecret, ["%mayeco_google.oauthinfo.client_secret%"]]
            - [setRedirectUri, ["%mayeco_google.oauthinfo.redirect_url%"]]
            - [setApplicationName, ["%mayeco_google.user_agent%"]]
            - [setScopes, ["%mayeco_google.oauthinfo.scopes%"]]
            - [setAccessType, ["%mayeco_google.oauthinfo.access_type%"]]
            - [setApprovalPrompt, ["%mayeco_google.oauthinfo.approval_prompt%"]]

    mayeco_google.adwordsuser:
        class: AdWordsUser
        public: false
        calls:
            - [SetDeveloperToken, ["%mayeco_google.adwords.dev_token%"]]
            - [SetDefaultVersion, ["%mayeco_google.adwords.lib_version%"]]
            - [SetUserAgent, ["%mayeco_google.user_agent%"]]
            - [SetClientLibraryUserAgent, ["%mayeco_google.user_agent%"]]
            - [SetOAuth2Info, ["%mayeco_google.oauthinfo%"]]

    google.utils:
        class: Mayeco\GoogleBundle\Services\GoogleUtils
        arguments: ["@mayeco_google.adwordsuser", "@mayeco_google.apiclient", "@memcache.default"]
