parameters:

    mayeco_google.apiclient.class: Google_Client
    mayeco_google.adwordsuser.class: AdWordsUser
    mayeco_google.utils.class: Mayeco\GoogleBundle\Services\GoogleUtils

services:
    mayeco_google.apiclient:
        class: %mayeco_google.apiclient.class%
        calls:
            - [setClientId, ["%mayeco_google.oauthinfo.client_id%"]]
            - [setClientSecret, ["%mayeco_google.oauthinfo.client_secret%"]]
            - [setRedirectUri, ["%mayeco_google.oauthinfo.redirect_url%"]]
            - [setApplicationName, ["%mayeco_google.user_agent%"]]
            - [addScope, ["%mayeco_google.oauthinfo.scope.email%"]]
            - [addScope, ["%mayeco_google.oauthinfo.scope.adwords%"]]
            - [setAccessType, ["offline"]]
            - [setApprovalPrompt, ["force"]]

    mayeco_google.adwordsuser:
        class: %mayeco_google.adwordsuser.class%
        calls:
            - [SetDeveloperToken, ["%mayeco_google.adwords.dev_token%"]]
            - [SetDefaultVersion, ["%mayeco_google.adwords.lib_version%"]]
            - [SetUserAgent, ["%mayeco_google.user_agent%"]]
            - [SetClientLibraryUserAgent, ["%mayeco_google.user_agent%"]]
            - [SetOAuth2Info, ["%mayeco_google.oauthinfo%"]]

    google.utils:
        class: %mayeco_google.utils.class%
        arguments: ["@mayeco_google.adwordsuser", "@mayeco_google.apiclient", "@memcache.default", "%google_adwordsapi_version%"]
